# Generated by Django 2.2 on 2020-07-22 09:49

import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=100)),
                ('bill_invoice', models.FileField(null=True, upload_to=core.helpers.PathAndRename('bills'))),
                ('bill_generated', models.BooleanField(default=True)),
                ('bill_invoiced', models.BooleanField(default=False)),
                ('bill_due_date', models.BooleanField(default=False)),
                ('bill_paid', models.BooleanField(default=False)),
                ('date_generated', models.DateTimeField(blank=True, null=True)),
                ('date_invoice_sent', models.DateTimeField(blank=True, null=True)),
                ('date_due_date', models.DateTimeField(blank=True, null=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('billed_to', models.ForeignKey(limit_choices_to={'user_type': 'CT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
