apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm-ibill-api-deployment
  labels:
    app: tm-ibill-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tm-ibill-api
  template:
    metadata:
      labels:
        app: tm-ibill-api
    spec:
      containers:
      - name: tm-ibill-api
        image: syafiqpipe/tm-ibill-api:1.0.10 #boleh tambah version
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
          - secretRef:
              name: tm-ibill-api-secret