# Generated by Django 2.2 on 2020-07-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CT', 'Customer'), ('BO', 'Business Operation - TM One'), ('BU', 'Business Operation - Unifi'), ('BW', 'Business Operation - TM Wholesale'), ('SA', 'System Admin'), ('SD', 'System Developer'), ('SS', 'System Suppport / Operation')], default='CT', max_length=2),
        ),
    ]
