# Generated by Django 2.2 on 2020-07-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='modified_date',
            new_name='modified_at',
        ),
    ]
